### ISSUE TITLE
Black Screen on libreelec 7.0.0 with 7.0.2

### ISSUE THREAD

**Issue by Dave-Kay** [kszaq/my-addons#4]
tightVNC eats the CPU
Ultra VNC is giving me a black Screen
And Real VNC is showing:
"RFB protocol error:bad desktop size 0x0"

But i'm desperate to get a working VNC for my headless RPi2...

**Comment by kszaq** [comment]
aml-vnc is for Amlogic devices only. You should use dispmanx-vnc for RPi2.
