### ISSUE TITLE
Support for S905 Android boxes

### ISSUE THREAD

**Issue by joeirsko** [kszaq/my-addons#5]
Hello,
thank you for your work and also for Libreelec builds for s905. I would like to use your vncserver on my S905 based box.  I checked the startup script and I added "set -x" and I am getting error "aml-vnc: not found".  I ran also binary manually and same error again.
See my attachment. I
It would be great if you can fix it and can use this vncserver addon. Thank you.
[script.output.txt](https://github.com/kszaq/my-addons/files/414067/script.output.txt)

**Comment by kszaq** [comment]
At the moment addon is compatible only with arm devices and not aarch64. The code needs to be adapted for aarch64 devices. I may do that in the future.

**Comment by kszaq** [comment]
Recent upload works on aarch64.
