### ISSUE TITLE
Compile build for 8.0.

### ISSUE THREAD

**Issue by ozkaradag** [kszaq/my-addons#6]
It doesnt work at ELEC 8.0.

Plaese, new build for 8.0.

Sincerelly...

**Comment by kszaq** [comment]
Can you try to download this release: https://github.com/kszaq/my-addons/releases/tag/7.0.3

I re-uploaded statically compiled binary, hopefully it will work on LE8.0 as well.

**Comment by ozkaradag** [comment]
hi @kszaq,

I installed it and it works excellent in LE 7.90.007.

Thank you very much.

Sincerelly...
